CREATE TABLE store_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    time_created TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE store_items 
    ADD COLUMN 
    user_id INTEGER REFERENCES store_users(id)
    ON DELETE SET NULL;